# Generated by Django 3.2.9 on 2021-11-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(blank=True, default='profile.jpg', upload_to='media/pro/'),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='media/apply/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.profile')),
            ],
        ),
    ]
