# Generated by Django 3.2.9 on 2021-11-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211109_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.profile'),
        ),
    ]
