# Generated by Django 3.2.9 on 2021-11-10 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_apply_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apply',
            name='documents',
            field=models.FileField(upload_to='media/apply/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])]),
        ),
    ]
